name: Deploy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          ADMIN_IDS: ${{ vars.ADMIN_IDS }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
          RUST_LOG: ${{ vars.RUST_LOG }}
        with:
          host: ${{ vars.SSH_HOST }}
          port: ${{ vars.SSH_PORT }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: ADMIN_IDS, DATABASE_URI, TELOXIDE_TOKEN, RUST_LOG
          script: |
            cd ${{ vars.PROJECT_DIR }}
            git stash
            git checkout main
            git pull origin main
            docker compose -f docker-compose.ci.yaml run --rm migrate
            docker compose -f docker-compose.ci.yaml up --build -d bot
